version: '3'

services:
  backend_service:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    image: gcr.io/my-project/backend_service:latest
    ports:
      - "8000:8000"

  frontend_app:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    image: gcr.io/my-project/frontend_app:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend_service:8000
