version: '3'

services:
  backend:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend_service:8000
