version: '3'

services:
  backend:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
      args:
        cloud_sql_connection_name: ${cloud_sql_connection_name}
        database_port: ${database_port}
        database_password: ${database_password}
        database_name: ${database_name}
        database_username: ${database_username}
        secret_key: ${secret_key}
        algorithm: ${algorithm}
        mail_api_key: ${mail_api_key}
        email_template_id: ${email_template_id}
        password_salt: ${password_salt}
        from_email: ${from_email}
        access_token_expire_minutes: ${access_token_expire_minutes}
        PROJECT_ID: ${PROJECT_ID}
        KUBERNETES_SERVICE_HOST: ${KUBERNETES_SERVICE_HOST}
    image: backend:latest
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend_service:8000
