apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: destination-service
  template:
    metadata:
      labels:
        app: destination-service
    spec:
      containers:
      - name: destination-service
        image: gcr.io/${PROJECT_ID}/backend:latest
        ports:
        - containerPort: 8000
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command: [ "/cloud_sql_proxy" ]
        args:
          - -instances=$(CLOUD_SQL_CONNECTION_NAME)=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
        env:
          - name: CLOUD_SQL_CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: cloudsql-connection-name
                key: CLOUD_SQL_CONNECTION_NAME
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: cloudsql-connection-name
            mountPath: /secrets/cloudsql-connection-name
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql-connection-name
          secret:
            secretName: cloudsql-connection-name
