apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: destinationsurf-tls
spec:
  secretName: destinationsurf-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - destinationsurf.com
