apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: frontend-ip
    kubernetes.io/ingress.class: "gce"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - destinationsurf.com
    secretName: destinationsurf-tls
  rules:
  - host: destinationsurf.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: destination-frontend
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: gce
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: destinationsurf-tls
spec:
  secretName: destinationsurf-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - destinationsurf.com
