apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: destination-service
  template:
    metadata:
      labels:
        app: destination-service
    spec:
      containers:
      - name: destination-service
        image: <your-registry>/<your-image>:<tag>
        ports:
        - containerPort: 8000
        env:
        - name: ENV_VAR_NAME
          value: ENV_VAR_VALUE
