"""add destination surf details

Revision ID: 081cb23e3a7a
Revises: e15f123e7cd0
Create Date: 2023-06-11 18:09:05.121454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081cb23e3a7a'
down_revision = 'e15f123e7cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_surf_details',
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('beginner_months', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('intermediate_months', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('expert_months', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('swell_colour', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('water_temp', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('weather', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destination_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination_surf_details')
    # ### end Alembic commands ###
