"""first

Revision ID: 113c73d2b1d3
Revises: 
Create Date: 2023-03-02 23:39:35.954032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '113c73d2b1d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=300), nullable=False),
                    sa.Column('address', sa.String(length=300), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('country', sa.String(length=100), nullable=False),
                    sa.Column('country_code', sa.String(length=3), nullable=False),
                    sa.Column('post_code', sa.String(length=20), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('accom_type_id', sa.Integer(), nullable=False),
                    sa.Column('booking_url', sa.String(length=800), nullable=True),
                    sa.Column('photo_url', sa.String(length=800), nullable=True),
                    sa.Column('url', sa.String(length=800), nullable=True),
                    sa.Column('date_added', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
                    sa.Column('date_updated', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('active', sa.BOOLEAN(), server_default='t', nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('accommodation_id',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    at_table = op.create_table('accommodation_type',
                        sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('type', sa.String(length=30), nullable=False),
                        sa.PrimaryKeyConstraint('type_id')
                        )
    op.bulk_insert(at_table,
                   [{'type': 'Apartments'},
                    {'type': 'Hotels'},
                    {'type': 'Guesthouses'},
                    {'type': 'Homestays'},
                    {'type': 'Resorts'},
                    {'type': 'Bed and Breakfasts'},
                    {'type': 'Villas'},
                    {'type': 'Hostels'},
                    {'type': 'Vacation Homes'},
                    {'type': 'Inns'},
                    {'type': 'Country Houses'},
                    {'type': 'Condo Hotels'},
                    {'type': 'Lodges'},
                    {'type': 'Resort Villages'},
                    {'type': 'Chalets'},
                    {'type': 'Campgrounds'},
                    {'type': 'Luxury tents'},
                    ]
                   )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=False),
                    sa.Column('second_name', sa.String(length=80), nullable=False),
                    sa.Column('first_line_address', sa.String(length=100), nullable=False),
                    sa.Column('second_line_address', sa.String(length=100), nullable=False),
                    sa.Column('city', sa.String(length=40), nullable=False),
                    sa.Column('country_code', sa.String(length=3), nullable=False),
                    sa.Column('post_code', sa.String(length=10), nullable=False),
                    sa.Column('date_of_birth', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=15), nullable=False),
                    sa.Column('registered_on', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
                    sa.Column('confirmed', sa.BOOLEAN(), server_default='f', nullable=False),
                    sa.Column('admin_flag', sa.BOOLEAN(), server_default='f', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('accommodation_id_mapping',
                    sa.Column('accommodation_id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.Integer(), nullable=False),
                    sa.Column('external_id_type', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['external_id_type'], ['accommodation_type.type_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('accommodation_id', 'external_id', 'external_id_type')
                    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('accommodation_id_mapping')
    op.drop_table('users')
    op.drop_table('accommodation_type')
    op.drop_table('accommodation_id')
    op.drop_table('accommodation')
    # ### end Alembic commands ###
