"""add surf filters

Revision ID: c7980b007bad
Revises: 12d197a9e47d
Create Date: 2023-06-12 21:21:58.288291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7980b007bad'
down_revision = '12d197a9e47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_surf_filters',
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('surf_lessons', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('surf_rental', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('yoga', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('less_1km_surf', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('co_working', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('co2Compensated', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('surfBreakAccess', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accommodation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accommodation_surf_filters')
    # ### end Alembic commands ###
