name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud auth configure-docker

    - name: Build and Push Docker Images
      env:
        DOCKER_BUILDKIT: 1
      run: |
        cd destination-service
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/destination-service:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/destination-service:${{ github.sha }}
        cd ../destination-frontend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/destination-frontend:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/destination-frontend:${{ github.sha }}

    - name: Apply Kubernetes Configuration
      run: |
        gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE}
        cd kubernetes
        kubectl apply -f destination-service.yaml
        kubectl apply -f destination-frontend.yaml



