name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker


    - name: Build and Push Docker Images
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker-compose build
        docker-compose push

    - name: Apply Kubernetes Configuration
      run: |
        gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${ZONE}
        kubectl apply -f k8s/backend_deployment.yaml
        kubectl apply -f k8s/backend_service.yaml
        kubectl apply -f k8s/frontend_deployment.yaml
        kubectl apply -f k8s/frontend_service.yaml




